import CatalogHeader from '@/components/shared/catalogHeader'
import type { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function CategoryLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<div>
			<CatalogHeader />
			{children}
		</div>
	)
}
